"""Stub for fastmcp so type checkers resolve the import when the package is not installed."""
from typing import Any, Callable

class FastMCP:
    def __init__(self, name: str = "", **kwargs: Any) -> None: ...
    def tool(self, fn: Callable[..., Any] | None = None, **kwargs: Any) -> Callable[..., Any]: ...
    def run(self, **kwargs: Any) -> None: ...
